name: Build MindTheGapps

on:
  workflow_dispatch:

jobs:  
  build:
    name: 13.0.0-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm64", "x86_64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone repository
        run: git clone -b tau https://gitlab.com/MindTheGapps/vendor_gapps.git/ --depth 1

      - name: Build
        working-directory: vendor_gapps
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          cp -f ../build.sh build/gapps.sh
          export PATH="/usr/local/lib/android/sdk/build-tools/34.0.0:$PATH"
          ./build/gapps.sh ${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.date }}
          fail_on_unmatched_files: true
          files: vendor_gapps/out/*.zip
          body: Updated on ${{ env.date }}
